version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      github-actions:
        patterns:
          - 'actions/*'
      codeql:
        patterns:
          - 'github/codeql-action/*'

  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/access-token-jwt'
      - '/packages/oauth2-bearer'
      - '/packages/express-oauth2-jwt-bearer'
      - '/packages/examples'
    schedule:
      interval: 'weekly'
