name: Return the version extracted from the branch name

#
# Returns the version from the .version file.
#
# TODO: Remove once the common repo is public.
#

inputs:
  working-directory:
    default: './'

outputs:
  version:
    value: ${{ steps.get_version.outputs.VERSION }}

runs:
  using: composite

  steps:
    - id: get_version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        VERSION=$(head -1 .version)
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT